obj-$(CONFIG_BMEM) += drivers/video/bmem/
obj-$(CONFIG_HANTRO) += drivers/video/hantro/
obj-$(CONFIG_GE) += drivers/video/ge/

obj-$(CONFIG_BRCM_HAL_CAM)  += drivers/char/brcm/hal_cam/
obj-$(CONFIG_VIDEO_CAMACQ)  += drivers/char/brcm/camacq/
obj-$(CONFIG_BRCM_HAL_CAM_WITH_STILL_YUV) += drivers/char/brcm/hal_cam/

obj-$(CONFIG_DPRAM) += drivers/char/sec/dpram/

obj-$(CONFIG_BRCM_FUSE_IPC_2153SDB) += drivers/char/brcm/fuse_ipc/
obj-$(CONFIG_BRCM_FUSE_IPC_2157SDB) += drivers/char/brcm/fuse_ipc/
obj-$(CONFIG_BRCM_FUSE_RPC_2157SDB) += drivers/char/brcm/fuse_rpc/
obj-$(CONFIG_BRCM_FUSE_RIL_2157SDB) += drivers/char/brcm/fuse_ril/
obj-$(CONFIG_BRCM_FUSE_IPC_CIB) += drivers/char/brcm/fuse_ipc/
obj-$(CONFIG_BRCM_FUSE_RPC_CIB) += drivers/char/brcm/fuse_rpc/
obj-$(CONFIG_BRCM_FUSE_RIL_CIB) += drivers/char/brcm/fuse_ril/
obj-$(CONFIG_BRCM_FUSE_NET) += drivers/char/brcm/fuse_net/
obj-$(CONFIG_BRCM_FUSE_AT) += drivers/char/brcm/fuse_at/
obj-$(CONFIG_BRCM_FUSE_PDP_CIB) += drivers/char/brcm/fuse_pdp/


obj-$(CONFIG_BRCM_FUSE_RIL_2153SDB) += drivers/char/brcm/fuse_rpc/

obj-$(CONFIG_BRCM_FUSE_RIL_2153SDB) += drivers/char/brcm/fuse_ril/
obj-$(CONFIG_BRCM_FUSE_LOG) += drivers/char/brcm/fuse_log/
obj-$(CONFIG_BRCM_FUSE_SYSPARM) += drivers/char/brcm/fuse_sysparm/
obj-$(CONFIG_BRCM_FUSE_VSP) += drivers/char/brcm/fuse_vsp/
obj-$(CONFIG_BRCM_XSCRIPT) += drivers/char/brcm/xscript/
obj-$(CONFIG_BRCM_V3D) += drivers/char/brcm/v3d/
ifeq ($(CONFIG_ARCH_BCM2157), y)
obj-$(CONFIG_BRCM_SOUND_ALSA) += drivers/sound/brcm/alsa/
endif

ifeq ($(CONFIG_ARCH_BCM215XX), y)
obj-$(CONFIG_BRCM_SOUND_ATHENA_ALSA) += drivers/sound/brcm/alsa_athena/
endif
# Headset module
obj-$(CONFIG_BRCM_HEADSET) += drivers/sound/brcm/headset/
#cntin
obj-$(CONFIG_BRCM_CNTIN) += drivers/gps/brcm/

